config/routes.rb
Rails.application.routes.draw do
  resources :rsa_fulls
  resources :messages
  root to: "rsas#new"

  match '/rsas' => 'rsa_fulls#create', via: :post
  match '/rsas/:id' => 'rsa_fulls#show', via: :get
  match '/rsas/:id/encrypt_messages/' => 'messages#create', via: :post
  match '/rsas/:id/encrypt_messages/:message_id' => 'messages#show', via: :get
  match '/rsas/:id/decrypt_messages/' => 'messages#decrypt', via: :post
  # POST /rsas - създава нов ключ и връща id на този ключ
  # POST /rsas - създава нов ключ с конкретните стойности за n, e, d. Връзка id-то
  #     params: n, e, d
  # GET /rsas/:id - връща json представяне на ключа с идентификатор id. JSON-а съдържа три ключа n, e, d със стойности на съответните параметри
  # POST /rsas/:id/encrypt_messages/ - криптира съобщението подадено с параметъра и създава ново криптирано съобщение. Връща идентификатор
  #     params: message
  # GET /rsas/:id/encrypt_messages/:id - връща криптирано съобщение с дадения идентификатор. JSON съдържа един ключ message със стойност съобщението
  # POST /rsas/:id/decrypt_messages/ - декриптира съобщението подадено с параметър и създава ново дикриптирано съобщение на база параметъра.
  #     params: message

  # For detail s on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# curl -H "Content-Type: application/json" -X POST -d '{"n": 19, "e": 14, "d": 48}' https://rsa-tp-hw.herokuapp.com/rsas

# curl -H "Content-Type: application/json" -X GET https://rsa-tp-hw.herokuapp.com/rsas/1

# curl -H "Content-Type: application/json" -X POST -d '{"message":"Supernatural school"}' https://rsa-tp-hw.herokuapp.com/rsas/1/encrypt_messages/

# curl -H "Content-Type: application/json" -X POST -d '{"message":"155.1881.926.936.2359.1368.362.1075.1881.2359.362.379.1552.761.263.2726.999.999.379"}' https://rsa-tp-hw.herokuapp.com/rsas/1/decrypt_messages/

# curl -H "Content-Type: application/json" -X GET https://rsa-tp-hw.herokuapp.com/rsas/1/encrypt_messages/1

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/rsa.rb
require 'prime'

class RSA
  def initialize n = nil, e = nil, d = nil
   @n = n.to_i
   @e = e.to_i
   @d = d.to_i
  end

  def n
    @n
  end

  def e
    @e
  end

  def d
    @d
  end

  def new_key
    keys = Array.new(3, 1)
    p = Prime.prime_division(rand(1000)).pop[0]
    q = Prime.prime_division(rand(1000)).pop[0]

    n = p*q
    keys[0] = n
    totient = (p-1)*(q-1)

    while ((e = rand(totient)) && e.gcd(totient) != 1)
    end
    keys[1] = e

    d = keys[2]

    while ((d * e)%totient != 1 && d = d + 1)
    end
    keys[2] = d

    keys
  end

  def encrypt message
    passed = message.split("").map! { |i|
      c = (i.ord)**@e
      i = c % @n
    }
    passed.join(".")
  end

  def decrypt message
    passed = message.split(".").map! { |i|
      m = i.to_i ** @d
      i = (m % @n).chr
    }
    passed.join("")
  end
end

app/models/rsa_full.rb
require 'prime'
require 'rsa'

class RsaFull < ApplicationRecord

  # after_initialize do |rsafull|
  #  @n = self[:n]
  #  @e = self[:e]
  #  @d = self[:d]
  # end

  def self.new_key
    rsa = RSA.new
    rsa.new_key
  end

  def encrypt message
    rsa = RSA.new(n, e, d)
    rsa.encrypt(message)
  end

  def decrypt message
    rsa = RSA.new(n, e, d)
    rsa.decrypt(message)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    message = Message.find_by id: params[:message_id]

    respond_to do |format|
      format.json { render json: { 'message' => message.content } }
    end
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    key = RsaFull.find_by id: params[:id]
    encrypted_message = key.encrypt(params[:message])
    message = Message.new(content: encrypted_message)

    message.save! # Will throw an error if invalid ( unlikely event) !
    respond_to do |format|
      format.json { render json: { 'id' => message.id } }
    end
  end

  def decrypt
    key = RsaFull.find_by id: params[:id]
    message = Message.new(content: key.decrypt(params[:message]))

    message.save! # Will throw an error if invalid ( unlikely event) !
    respond_to do |format|
      format.json {render json: {'id' => message.id, 'message' => message.content}}
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/rsa_fulls_controller.rb
class RsaFullsController < ApplicationController
  before_action :set_rsa_full, only: [:show, :edit, :update, :destroy]

  # GET /rsa_fulls
  # GET /rsa_fulls.json
  def index
    @rsa_fulls = RsaFull.all
  end

  # GET /rsa_fulls/1
  # GET /rsa_fulls/1.json
  def show
    my_rsa = RsaFull.find_by id: params[:id]
    respond_to do |format|
         format.json {render json: {'n' => my_rsa.n, 'e' => my_rsa.e, 'd' => my_rsa.d}}
     end
  end

  # GET /rsa_fulls/new
  def new
    @rsa_full = RsaFull.new
  end

  # GET /rsa_fulls/1/edit
  def edit
  end

  # POST /rsa_fulls
  # POST /rsa_fulls.json
  def create

    keys = [params[:n], params[:e], params[:d]]
    # keys = [:n, :e, :d]
    if (params.keys && keys).any?
      my_rsa = RsaFull.new(n: params[:n], e: params[:e], d: params[:d])
    else
      keys = RsaFull.new_key
      my_rsa = RsaFull.new(n: keys[0], e: keys[1], d: keys[2])
    end
    respond_to do |format|
       if my_rsa.save
         format.json {render json: {'id' => my_rsa.id}}###
       end
     end
  end

  # PATCH/PUT /rsa_fulls/1
  # PATCH/PUT /rsa_fulls/1.json
  def update
    respond_to do |format|
      if @rsa_full.update(rsa_full_params)
        format.html { redirect_to @rsa_full, notice: 'Rsa full was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsa_full }
      else
        format.html { render :edit }
        format.json { render json: @rsa_full.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsa_fulls/1
  # DELETE /rsa_fulls/1.json
  def destroy
    @rsa_full.destroy
    respond_to do |format|
      format.html { redirect_to rsa_fulls_url, notice: 'Rsa full was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsa_full
      @rsa_full = RsaFull.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsa_full_params
      params.require(:rsa_full).permit(:n, :e, :d)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rsa_fulls_helper.rb
module RsaFullsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RsaCat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :message_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/rsa_fulls/_form.html.erb
<%= form_with(model: rsa_full, local: true) do |form| %>
  <% if rsa_full.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rsa_full.errors.count, "error") %> prohibited this rsa_full from being saved:</h2>

      <ul>
      <% rsa_full.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :n %>
    <%= form.number_field :n, id: :rsa_full_n %>
  </div>

  <div class="field">
    <%= form.label :e %>
    <%= form.number_field :e, id: :rsa_full_e %>
  </div>

  <div class="field">
    <%= form.label :d %>
    <%= form.number_field :d, id: :rsa_full_d %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rsa_fulls/edit.html.erb
<h1>Editing Rsa Full</h1>

<%= render 'form', rsa_full: @rsa_full %>

<%= link_to 'Show', @rsa_full %> |
<%= link_to 'Back', rsa_fulls_path %>

app/views/rsa_fulls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rsa Fulls</h1>

<table>
  <thead>
    <tr>
      <th>N</th>
      <th>E</th>
      <th>D</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsa_fulls.each do |rsa_full| %>
      <tr>
        <td><%= rsa_full.n %></td>
        <td><%= rsa_full.e %></td>
        <td><%= rsa_full.d %></td>
        <td><%= link_to 'Show', rsa_full %></td>
        <td><%= link_to 'Edit', edit_rsa_full_path(rsa_full) %></td>
        <td><%= link_to 'Destroy', rsa_full, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsa Full', new_rsa_full_path %>

app/views/rsa_fulls/new.html.erb
<h1>New Rsa Full</h1>

<%= render 'form', rsa_full: @rsa_full %>

<%= link_to 'Back', rsa_fulls_path %>

app/views/rsa_fulls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>N:</strong>
  <%= @rsa_full.n %>
</p>

<p>
  <strong>E:</strong>
  <%= @rsa_full.e %>
</p>

<p>
  <strong>D:</strong>
  <%= @rsa_full.d %>
</p>

<%= link_to 'Edit', edit_rsa_full_path(@rsa_full) %> |
<%= link_to 'Back', rsa_fulls_path %>